### ISSUE TITLE
Runing of ECPred on plants data ?

### ISSUE THREAD

**Issue by anani-a-missinou** [cansyl/ECPred#4]
Hi, 

Can I apply your tools on plant data that contained many genes from polyploidization and tandem duplication? So potentially neofunctionalization or sub-functionalization of genes. Thanks

**Comment by alperendalkiran** [comment]
Yes, you may use ECPred on your data. We used the tool on metagenomics sequencing data for genome annotations. Metagenome data is in a way similar to your data. Don’t forget to translate your plant ORF data in amino acid sequences, since ECpred works with protein sequences, good luck.

**Comment by anani-a-missinou** [comment]
Thank you for your answer.

I try to install ECPred on Virtual Ubuntu 18 machine install on Cluster. by this following script

sudo apt-get install default-jre
sudo apt-get install default-jdk

wget https://ucfa50bebca5bb3d75722c012574.dl.dropboxusercontent.com/cd/0/get/AwGEe7EWD7EQ48aCNJg-DSPK_oTK7PFFjjmZw7bvzA303TOAl1tEs1OnPBCc6vP0oH1bu5S95Fs13-DOCtX5DWXObc2pZiSx5Ju4sHrM_78CMA/file?dl=1# 
wget https://goo.gl/g2tMJ4

This file download return this file ‘file?dl=1’ which is not zipped. 
I think it incorrectly downloads of ECPred.tar.gz file which normally contained all required files including ECPred.jar when I download on my windows system. 

ECPred\lib
ECPred\ECPred.jar
ECPred\ECPred_woH.jar
ECPred\ECNumberList.txt
ECPred\README
ECPred\README_woH
ECPred\results.tsv
ECPred\runLinux.sh
ECPred\runMac.sh
ECPred\sample.fasta

Please, can you help me with the correct installation and use it.

**Comment by alperendalkiran** [comment]
Could you please re-download using the following command,
wget -O ECPred.tar.gz https://goo.gl/g2tMJ4
