### ISSUE TITLE
train the model from scratch

### ISSUE THREAD

**Issue by dsaeedeh** [cansyl/ECPred#9]
I want to train the model on my own dataset. I could not find the training part of the model. Could you please help me with how I can train the model from scratch? Thanks.

**Comment by alperendalkiran** [comment]
I am afraid training from scratch is not possible. However, I found the source of the error. libidn11 should be installed on your computer.
First, you need to download it using the following command,
wget http://mirrors.kernel.org/ubuntu/pool/main/libi/libidn/libidn11_1.33-2.2ubuntu2_amd64.deb
then you can install it with this command,
sudo dpkg -i  libidn11_1.33-2.2ubuntu2_amd64.deb
Now you should be able to get predictions for the sample.fasta. Please let me know if you have further questions.

**Comment by dsaeedeh** [comment]
Thanks for your help. It works now! I'll put the link to your solution in the previous issue for future reference.
